# Generated by Django 5.0.4 on 2024-05-05 12:06

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, unique=True, validators=[App.models.validate_title_length]),
        ),
    ]
